# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [13]:
np.__version__
np.__config__.CONFIG

{'Compilers': {'c': {'name': 'gcc',
   'linker': 'ld.bfd',
   'version': '10.2.1',
   'commands': 'cc',
   'args': '-fno-strict-aliasing',
   'linker args': '-Wl,--strip-debug, -fno-strict-aliasing'},
  'cython': {'name': 'cython',
   'linker': 'cython',
   'version': '3.0.8',
   'commands': 'cython'},
  'c++': {'name': 'gcc',
   'linker': 'ld.bfd',
   'version': '10.2.1',
   'commands': 'c++',
   'linker args': '-Wl,--strip-debug'}},
 'Machine Information': {'host': {'cpu': 'x86_64',
   'family': 'x86_64',
   'endian': 'little',
   'system': 'linux'},
  'build': {'cpu': 'x86_64',
   'family': 'x86_64',
   'endian': 'little',
   'system': 'linux'}},
 'Build Dependencies': {'blas': {'name': 'openblas64',
   'found': True,
   'version': '0.3.23.dev',
   'detection method': 'pkgconfig',
   'include directory': '/usr/local/include',
   'lib directory': '/usr/local/lib',
   'openblas configuration': 'USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS= NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1

#### 3. Create a null vector of size 10 (★☆☆)

In [37]:
np.empty((2, 5))

array([[ 5.37733536e-310,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  6.67919395e-310],
       [ 3.92081605e+179,  3.21443142e-057,  4.26786255e-090,
         1.27937754e+161, -5.01170858e+067]])

#### 4. How to find the memory size of any array (★☆☆)

we get the size (total number of elements) of the array be using the **(size)** attribute
- let this be **n**

we get the size of each item based on its type using the **(itemsize)** attribute 
- let this be n

Hence the memory size of the array is goven by;

**size * itemsize** ==> n * i

In [387]:
arr = np.tile(np.array([[4, 3], [2, 1]]), (2, 3))
arr

array([[4, 3, 4, 3, 4, 3],
       [2, 1, 2, 1, 2, 1],
       [4, 3, 4, 3, 4, 3],
       [2, 1, 2, 1, 2, 1]])

In [390]:
arr[1:3, [1,3, 5]]

array([[1, 1, 1],
       [3, 3, 3]])

In [391]:
np.triu?

Signature:       np.triu(m, k=0)
Call signature:  np.triu(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function triu at 0x7af4ddce9360>
File:            ~/.local/lib/python3.10/site-packages/numpy/lib/twodim_base.py
Docstring:      
Upper triangle of an array.

Return a copy of an array with the elements below the `k`-th diagonal
zeroed. For arrays with ``ndim`` exceeding 2, `triu` will apply to the
final two axes.

Please refer to the documentation for `tril` for further details.

See Also
--------
tril : lower triangle of an array

Examples
--------
>>> np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])

>>> np.triu(np.arange(3*4*5).reshape(3, 4, 5))
array([[[ 0,  1,  2,  3,  4],
        [ 0,  6,  7,  8,  9],
        [ 0,  0, 12, 13, 14],
        [ 0,  0,  0, 18, 19]],
       [[20, 21, 22, 23, 24],
        [ 0, 26, 27, 28, 29],
        [ 0,  0, 32, 33, 34],
        [ 0,

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [38]:
help(np.add)

Help on ufunc:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [46]:
x = np.zeros((10, ))
x[4] = 1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [345]:
arr =np.arange(10, 50)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [359]:
# reverse the last array above
# index = np.arange(-1, -41, -1)
# arr[index]

arr[40: :-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [130]:
np.arange(0, 9).reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [137]:
arr = np.array([1, 2, 0, 0, 4, 0]).reshape(2, 3)

arr.nonzero()

(array([0, 0, 1]), array([0, 1, 1]))

#### 11. Create a 3x3 identity matrix (★☆☆)

In [140]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [194]:
np.random.random((3, 3, 3))

array([[[0.1861899 , 0.57357319, 0.56453777],
        [0.53528256, 0.9829368 , 0.28234572],
        [0.30044266, 0.02915497, 0.43924663]],

       [[0.21402631, 0.0519521 , 0.05339774],
        [0.87531099, 0.24182699, 0.56701368],
        [0.00985506, 0.51466076, 0.06877981]],

       [[0.78887483, 0.23418367, 0.31091068],
        [0.59889853, 0.17553231, 0.03280139],
        [0.66864528, 0.44082272, 0.59075855]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [209]:
arr = np.random.random((10, 10))

minimum = arr.min()
maximum = arr.max()

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [214]:
np.random.random(size=(30)).mean()

0.5969740439468324

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [247]:
# we have to take a slice that does not contain the ... 
# first row and last rows, and the 
# first and last column
arr = np.ones((7, 7))

# first and last correspond to (0, 7)
arr[1:6, 1:6] = 0

arr

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [253]:
# we select a slice containing the borders only (firs and last - rows and columns)

# e.g. say we have the arrays
arr = np.arange(64).reshape((8, 8))

# select the first and last rows 
arr[[0, 7]] = 0

# select the first and last columns
arr[:, [0, 7]] = 0

arr

array([[ 0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  9, 10, 11, 12, 13, 14,  0],
       [ 0, 17, 18, 19, 20, 21, 22,  0],
       [ 0, 25, 26, 27, 28, 29, 30,  0],
       [ 0, 33, 34, 35, 36, 37, 38,  0],
       [ 0, 41, 42, 43, 44, 45, 46,  0],
       [ 0, 49, 50, 51, 52, 53, 54,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan # return nan (acts like a float)
np.nan == np.nan #  not false (assumes they are two different float)
np.inf > np.nan # false since nan is not a number
np.nan - np.nan # return the same thing
np.nan in set([np.nan]) # true
0.3 == 3 * 0.1 # false due to floating point arithmetic
```

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [341]:
# we flatten the array and get the index of the non-zero index
# get a slice of the array and use the index to change the data

# create a (5, 5) identity matrix with 1's just below the main diagonal
arr = np.eye(5, k=-1)

# using fancy indexing
arr[[ 1, 2, 3, 4], [[0, 1, 2, 3]]] = [1, 2, 3, 4]

# discovered this simpler method solution while going through the scipy lecture notes on NumPy 
d = np.diag([1, 2, 3, 4], k=-1)

# check that they return the same thing
d == arr

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [314]:
# without using the eye method; the only requirement is that the order of the matrix must be known to perform the sub-indexes

arr = np.arange(25).reshape((5, 5))

print(arr)

arr[[1, 2, 3, 4], [0, 1, 2, 3]] = [1, 2, 3, 4]
arr

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[ 0,  1,  2,  3,  4],
       [ 1,  6,  7,  8,  9],
       [10,  2, 12, 13, 14],
       [15, 16,  3, 18, 19],
       [20, 21, 22,  4, 24]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [339]:
# create an (8,8) matrix and fill it with alternating true and false 
# then use the where method to find to assing a patter if element is true and otherwise

# utilize even number property
arr = np.arange(2, 129,  2).reshape((8, 8))
# cond = ar
arr

array([[  2,   4,   6,   8,  10,  12,  14,  16],
       [ 18,  20,  22,  24,  26,  28,  30,  32],
       [ 34,  36,  38,  40,  42,  44,  46,  48],
       [ 50,  52,  54,  56,  58,  60,  62,  64],
       [ 66,  68,  70,  72,  74,  76,  78,  80],
       [ 82,  84,  86,  88,  90,  92,  94,  96],
       [ 98, 100, 102, 104, 106, 108, 110, 112],
       [114, 116, 118, 120, 122, 124, 126, 128]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

#### 22. Normalize a 5x5 random matrix (★☆☆)

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)